# Generated by Django 5.1.6 on 2025-02-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_auto_20250125_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonate',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
