# Generated by Django 5.1.6 on 2025-02-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0004_alter_blooddonate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonate',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
