# Generated by Django 5.1.6 on 2025-02-16 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0006_rename_name_blooddonate_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blooddonate',
            name='first_name',
        ),
    ]
