# Generated by Django 5.1.6 on 2025-02-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0007_remove_blooddonate_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='bloodgroup',
            field=models.CharField(default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
